# Numpy Operations

NumPy stands for numeric python which is a python package for the computation and processing of the multidimensional and single dimensional array elements.

Reshaping a Numpy Array,
Indexing & Slicing a NumPy Array,
Replacing the elements in Numpy Array,
Manipulating NumPy Array,
Performing Mathematical & Statistical Functions using NumPy

In [2]:
import numpy as np

In [2]:
np.array([-2,3,4,5],dtype=bool)

array([ True,  True,  True,  True])

In [5]:
5/0

ZeroDivisionError: division by zero

In [8]:
a=np.array([[1,2,3,4],[6,7,8,9],[7,8,9,10],[21,23,34,54]])

In [9]:
a[[0,1,3],2:]

array([[ 3,  4],
       [ 8,  9],
       [34, 54]])

In [10]:
a.flatten()

array([ 1,  2,  3,  4,  6,  7,  8,  9,  7,  8,  9, 10, 21, 23, 34, 54])

In [11]:
a.ravel()

array([ 1,  2,  3,  4,  6,  7,  8,  9,  7,  8,  9, 10, 21, 23, 34, 54])

In [15]:
s="abing"
if len(s)<3:
    s+="ing"
elif "ing" in s:
    s+="ly"
s

'abingly'

In [17]:
a=np.array([0,0,0,0,0,0,0,0,0,0,0])

In [18]:
a[6]=11

In [19]:
a

array([ 0,  0,  0,  0,  0,  0, 11,  0,  0,  0,  0])

In [23]:
a=np.zeros((8,8),dtype=int)

In [29]:
a[::2,::2]=1

In [33]:
a[1::2,1::2]=1

In [34]:
a

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [36]:
a=np.ones((3,2))

In [37]:
a*2

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [39]:
a=np.array([[1,2,3,4,5],[1,2,3,4,5]])

In [40]:
a[a%2==1]=-1

In [41]:
a

array([[-1,  2, -1,  4, -1],
       [-1,  2, -1,  4, -1]])

In [43]:
r=np.random.randint(-50,50,10)

In [44]:
r[r<0]=-1

In [45]:
r

array([15, -1, -1, 33, -1,  5, -1, -1, 42, 11])

In [8]:
a=np.arange(1,50)

In [9]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [12]:
for i in a:
    if i%3==0 and i%5==0:
        print('FrizzBuzz',i)
    elif i%5==0:
        print("Buzz",i)
    elif i%3==0:
        print("Fizz",i)

Fizz 3
Buzz 5
Fizz 6
Fizz 9
Buzz 10
Fizz 12
FrizzBuzz 15
Fizz 18
Buzz 20
Fizz 21
Fizz 24
Buzz 25
Fizz 27
FrizzBuzz 30
Fizz 33
Buzz 35
Fizz 36
Fizz 39
Buzz 40
Fizz 42
FrizzBuzz 45
Fizz 48


In [15]:
a=np.arange(1,10)

In [16]:
a.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])